version: '3.8'

services:
  php:
    image: php:8.1-cli
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST={DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TEST_DB_HOST={TEST_DB_HOST}
      - TEST_DB_NAME=${TEST_DB_NAME}
      - TEST_DB_USER=${TEST_DB_USER}
      - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}
    depends_on:
      - mysql
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: